---
title: "Females and health expenditure"
output: html_notebook
---
Female age and spouse

```{r}
TotalExpenditure_agefemalespousesplit_means_svyby<-as.data.frame(svyby(~TOTEXP, by=~SIXTYFIVEPLUS+SPOUIN_fac, design=subset(mepsdsgn,SEX_fac=="Female" & SPOUIN_fac!="Under 16 NA"), FUN = svymean))

print(TotalExpenditure_agefemalespousesplit_means_svyby)
```

```{r}
plot_totexpSpouseAgeFemale_w<-ggplot(TotalExpenditure_agefemalespousesplit_means_svyby[1:2,c(1,3:4)], aes(x=SIXTYFIVEPLUS,group = 1))
plot_totexpSpouseAgeFemale_w+geom_ribbon(aes(fill = "Spouse",ymin = TOTEXP - se, ymax = TOTEXP + se),alpha=0.5) + geom_line(aes(color="Spouse",y = TOTEXP))+geom_ribbon(data=TotalExpenditure_agefemalespousesplit_means_svyby[3:4,c(1,3:4)],aes(fill = "No Spouse",ymin = TOTEXP - se, ymax = TOTEXP + se),alpha=0.5) + geom_line(data=TotalExpenditure_agefemalespousesplit_means_svyby[3:4,c(1,3:4)],aes(color="No Spouse",y = TOTEXP)) + labs(x="Marital status",y="Mean total expenditure",title="Females mean total expenses by spouse and age")+theme(plot.title = element_text(hjust = 0.5))+guides(color=FALSE,fill=guide_legend(title="Age group"))
```